// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieManagement.Server.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieManagement.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250220140650_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.ChiTietBanVe", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("text");

                    b.Property<int>("MaGhe")
                        .HasColumnType("integer");

                    b.Property<int>("GiaVe")
                        .HasColumnType("integer");

                    b.HasKey("MaHoaDon", "MaGhe");

                    b.ToTable("CHITIETBANVE");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.ChiTietTheLoai", b =>
                {
                    b.Property<int>("MaPhim")
                        .HasColumnType("integer");

                    b.Property<int>("MaTheLoai")
                        .HasColumnType("integer");

                    b.HasKey("MaPhim", "MaTheLoai");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("CHITIETTHELOAI");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.Ghe", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGhe"));

                    b.Property<string>("Hang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LoaiGhe")
                        .HasColumnType("integer");

                    b.Property<int>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<int>("SoGhe")
                        .HasColumnType("integer");

                    b.HasKey("MaGhe");

                    b.HasIndex("MaPhong");

                    b.ToTable("GHE");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.GiaVePhim", b =>
                {
                    b.Property<int>("MaGiaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGiaVe"));

                    b.Property<int>("DoiTuong")
                        .HasColumnType("integer");

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("numeric");

                    b.Property<int>("LoaiNgay")
                        .HasColumnType("integer");

                    b.Property<int>("MocGio")
                        .HasColumnType("integer");

                    b.Property<int>("PhienBan")
                        .HasColumnType("integer");

                    b.HasKey("MaGiaVe");

                    b.ToTable("GIAVE");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.HoaDonBanVe", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("text");

                    b.Property<decimal>("DiemDoiVe")
                        .HasColumnType("numeric");

                    b.Property<int>("MaKhuyenMai")
                        .HasColumnType("integer");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaPhim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaThanhVien")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NhanVienMaNhanVien")
                        .HasColumnType("text");

                    b.Property<int>("SoLuongDoiVe")
                        .HasColumnType("integer");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("numeric");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("XuatChieu")
                        .HasColumnType("interval");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("HOADONBANVE");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.KhuyenMai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasColumnType("text");

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("GiamGiaVe")
                        .HasColumnType("numeric");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MaKhuyenMai");

                    b.ToTable("KHUYENMAI");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("text");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CapDo")
                        .HasColumnType("integer");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("integer");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("MaNhanVien");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.Phim", b =>
                {
                    b.Property<int>("MaPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhim"));

                    b.Property<string>("DaoDien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DienVien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhienBan")
                        .HasColumnType("integer");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("integer");

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MaPhim");

                    b.ToTable("PHIM");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.PhongChieu", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhong"));

                    b.Property<int>("CotGhe")
                        .HasColumnType("integer");

                    b.Property<int>("HangGhe")
                        .HasColumnType("integer");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TongSoGhe")
                        .HasColumnType("integer");

                    b.HasKey("MaPhong");

                    b.ToTable("PHONGCHIEU");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.ThanhVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("text");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiemTichLuy")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("integer");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("MaNhanVien");

                    b.ToTable("THANHVIEN");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.TheLoai", b =>
                {
                    b.Property<int>("MaTheLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTheLoai"));

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaTheLoai");

                    b.ToTable("THELOAI");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.XuatChieuPhim", b =>
                {
                    b.Property<int>("MaPhim")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("XuatChieu")
                        .HasColumnType("interval");

                    b.HasKey("MaPhim");

                    b.ToTable("XUATCHIEU");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.ChiTietBanVe", b =>
                {
                    b.HasOne("MovieManagement.Server.Models.Entities.HoaDonBanVe", "HoaDonBanVe")
                        .WithMany()
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDonBanVe");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.ChiTietTheLoai", b =>
                {
                    b.HasOne("MovieManagement.Server.Models.Entities.Phim", "Phim")
                        .WithMany()
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieManagement.Server.Models.Entities.TheLoai", "TheLoai")
                        .WithMany()
                        .HasForeignKey("MaTheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.Ghe", b =>
                {
                    b.HasOne("MovieManagement.Server.Models.Entities.PhongChieu", "PhongChieu")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongChieu");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.HoaDonBanVe", b =>
                {
                    b.HasOne("MovieManagement.Server.Models.Entities.NhanVien", null)
                        .WithMany("HoaDonBanVes")
                        .HasForeignKey("NhanVienMaNhanVien");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.XuatChieuPhim", b =>
                {
                    b.HasOne("MovieManagement.Server.Models.Entities.Phim", "Phim")
                        .WithMany()
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");
                });

            modelBuilder.Entity("MovieManagement.Server.Models.Entities.NhanVien", b =>
                {
                    b.Navigation("HoaDonBanVes");
                });
#pragma warning restore 612, 618
        }
    }
}
